### ISSUE TITLE
Logger should be replaced Vert.x Logger

### ISSUE THREAD

**Issue by cescoffier** [weld/weld-vertx#1]
Vert.x provides a small set of logger wrapper so it delegates to the configure backend.
Instead of JUL, it would be great to use this logger.

```
io.vertx.core.logging.LoggerFactory;
io.vertx.core.logging.Logger;
//...
Logger logger = LoggerFactory.getLogger(your_class);
```

The proposed API is very close (to not say similar) to the JUL one.

**Comment by mkouba** [comment]
@cescoffier Thanks for report. Fixed.
