### ISSUE TITLE
Add project to vert.x awesome

### ISSUE THREAD

**Issue by cescoffier** [weld/weld-vertx#2]
It would be great to have this project listed on https://github.com/vert-x3/vertx-awesome.

Just open a PR adding it to the README file.

**Comment by mkouba** [comment]
@cescoffier I'm not quite sure where to place this poject. It's just a prototype in a very early stage. I would wait until it gets a solid shape. What do you think?

**Comment by cescoffier** [comment]
It seems quite advanced to me. It's up to you.

vert.x awesome does not only contain "mature" project, but also pocs and demos (just need to write it in the description).
