### ISSUE TITLE
weld core for vertx-environment?

### ISSUE THREAD

**Issue by nimo23** [weld/weld-vertx#22]
Is it possible to use https://github.com/weld/core (weld 3.0 in java se) in vertx-environment as it is? If not, would be nice to provide support for vertx.

**Comment by mkouba** [comment]
Hi @nimo23, I'm not sure that I completely understand your question. `weld-vertx` is tested with Weld 3.0.0.Final.

**Comment by nimo23** [comment]
I was not sure about "weld-core".
Is "weld-core" (for SE) fully usable in vertx environment? I come from jee world and want to use weld as it is in vertx environment. 

So I guess, if I want to use weld-core, then I have to use weld-vertx (which includes weld-core). Am I right?

**Comment by mkouba** [comment]
Yes, `weld-vertx` is a good starting point. Take a look at:
* http://weld.cdi-spec.org/news/2016/04/11/weld-meets-vertx/
* http://weld.cdi-spec.org/news/2016/06/21/update-on-weld-vertx/
* https://github.com/weld/weld-vertx/blob/master/README.md

to make an idea of how the current integration works...

**Comment by nimo23** [comment]
ok, thanks!
