### ISSUE TITLE
Does it support vertx 4.x?

### ISSUE THREAD

**Issue by Ikki-Dai** [weld/weld-vertx#43]
does it support vertx 4.x? 
or provide roadmap

**Comment by manovotn** [comment]
Hello,

no it doesn't and this project is no longer developed and will be archived.
If you are looking for an alternative, I suggest you look at [Quarkus](https://quarkus.io/) which offers the CDI-Vertx functionalities this project had.

**Comment by mkouba** [comment]
Matej is right, `weld-vertx` does not support vert.x 4 and there is no plan to implement the support in the future.

Some of the core features were adopted in Quarkus, e.g.:
- `@Observes @VertxConsumer("echo.address") VertxEvent` -> https://quarkus.io/guides/reactive-event-bus#consuming-events
- `@WebRoute` -> https://quarkus.io/guides/reactive-routes
