### ISSUE TITLE
Integrate with Vert.x Service Proxies

### ISSUE THREAD

**Issue by vietj** [weld/weld-vertx#9]
Vert.x provides Service Proxies for doing async RPC : https://github.com/vert-x3/vertx-service-proxy

Such proxies could be integrated in Weld such as the proxies callbacks are dispatched by Weld during the event loop callback.

It would be useful for integrating a CDI application with Vert.x based services.

cc @emmanuelbernard @cescoffier

**Comment by mkouba** [comment]
Hi Julien,
what exactly should the integration do? Let's say we have a service interface `FooService` and impl `FooServiceImpl` registered on the bus with address `foo-service`. A client can create a service proxy with `ProxyHelper.createProxy()` and make use of it.

> Such proxies could be integrated in Weld such as the proxies callbacks are dispatched by Weld during the event loop callback.

Do you mean to dispatch a proxy invocation to a CDI bean or an observer method? I.e. to build a `FooService` implementation delegating to CDI components?

I'm sorry to be so slow ;-). A brief example would be useful.

**Comment by vietj** [comment]
I mean a Vert.x EventBus Service Proxy could be injected as a CDI Bean to talk to Vert.x EventBus Service Stub (these stub can be local or remote). This would allow to integrate Vert.x applications as services deployed in Vert.x and CDI could interact with these services using this proxy.

```
public class MyCDIApp {
   @Inject
   SomeVertxService service

   public void foo() {
      service.doSomething(result -> {
         // On CDI thread and not on Vert.x thread
      });
   }
}
```

**Comment by mkouba** [comment]
I think I'm getting closer ;-) So we can scan all service interfaces annotated with `@ProxyGen` and then create a dependent bean which would delegate to the original proxy (obtained by `ProxyHelper.createProxy()`) and wrap `Handler<AsyncResult<?>>` method params so that it's executed as a blocking code.

**Comment by mkouba** [comment]
@vietj I've created https://github.com/weld/weld-vertx/pull/12. Let me know what you think.

cc @emmanuelbernard @cescoffier

**Comment by vietj** [comment]
@mkouba great I'll comment on the issue
